
const artist = ["The Beatles", "Bob Dylan", "Elvis Presley", 
"The Rolling Stones", "Chuck Berry", "Jimi Hendrix", "James Brown",
 "Little Richard", "Aretha Franklin", "Ray Charles", "Bob Marley", 
"The Beach Boys", "Buddy Holly", "Led Zeppelin", "Stevie Wonder",
"Sam Cooke", "Muddy Waters", "Marvin Gaye", "The Velvet Underground",
"Bo Diddley", "Otis Redding", "U2", "Bruce Springsteen", "Jerry Lee Lewis",
"Fats Domino", "Ramones", "Prince", "The Clash", "The Who", "Nirvana", "Johnny Cash",
"Smokey Robinson and The Miracles", "The Everly Brothers", "Neil Young", "Michael Jackson",
"Madonna", "Roy Orbison", "John Lennon", "David Bowie", "Simon and Garfunkel", "The Doors",
"Van Morrison", "Sly & the Family Stone", "Public Enemy", "The Byrds", "Janis Joplin",
"Patti Smith", "Run-DMC", "Elton John", "The Band", "Pink Floyd", "Queen", 
"The Allman Brothers Band", "Howlin' Wolf", "Eric Clapton", "Dr. Dre", "Grateful Dead",
"Parliament/Funkadelic", "Aerosmith", "Sex Pistols", "Metallica", "Joni Mitchell",
"Tina Turner", "Phil Spector", "The Kinks", "Al Green", "Cream", "The Temptations",
"Jackie Wilson", "The Police", "Frank Zappa", "AC/DC", "Radiohead", "Hank Williams",
"Eagles", "The Shirelles", "Beastie Boys", "The Stooges", "Four Tops", "Elvis Costello",
"The Drifters", "Creedence Clearwater Revival", "Eminem", "James Taylor", "Black Sabbath",
"Tupac Shakur", "Gram Parsons", "Jay-Z", "The Yardbirds", "Carlos Santana", "Tom Petty",
"Guns N' Roses", "Booker T. and the MGs", "Nine Inch Nails", "Lynyrd Skynyrd",
"Diana Ross and The Supremes", "R.E.M.", "Curtis Mayfield", "Carl Perkins", "Talking Heads",
"Bad Bunny", "Harry Styles", "Post Malone", "The Weeknd", "Drake", "BTS", "Ed Sheeran",
"Alexander Acha", "David Aguilar", "Leonardo Aguilar", "Alan (actor)", "Alan Jacques", "Pepe Albarrán",
"Rubén Albarrán", "Alberto Ángel «El Cuervo»", "Julio Aldama", "Fernando Allende", "Julión Álvarez",
"Agustín Arana", "Miguel S. Arrevalo", "Ramón Armengod", "Felipe Arriaga", "Juan Arvizu", "Asaid",
"Hugo Avendaño", "Luis Manuel Ávila", "Francisco Avitia", "Paco Ayala", "Ramón Ayala (cantante mexicano)",
"B", "Antonio Badú", "Luigi Balestra", "Áureo Baqueiro", "Porfirio Bas", "Francisco Xavier Berganza",
"Claudio Bermúdez", "Ricardo Bernal (tenor)", "Konan Big", "Jorge Blanco (actor)", "Diego Boneta",
"Ari Borovoy", "Japhet Bravo", "Usuario:Briam jersy/Taller", "Guillermo Briseño",
"Laureano Brizuela (cantante)", "Enrique Cáceres Méndez", "Caloncho", "Guillermo Capetillo",
"Guty Cárdenas", "Antonio De Carlo", "Carlos Rivera", "Menny Carrasco",
"Mario Carrillo Inchaústegui", "Álvaro Carrillo Alarcón", "Cristian Castro",
"Cepillín", "Chabelo", "Chao (actor)", "Omar Chaparro", "Tino Contreras", "Chamín Correa",
"César Costa", "Coyote Dax", "Ernesto D'Alessio", "Pedro Dabdoub", "Toño de la Villa",
"Emmanuel del Real", "Luis Demetrio", "Aarón Díaz", "Alberto Dogre", "Mario Domm", "Don Cheto",
"Larry Donas", "Jean Douvenger", "Jack Duarte", "Michel Duval", "Randy Ebright", "El Komander",
"Erick Elías", "Francisco Elizalde", "Valentín Elizalde", "Erk Aicrag", "Ángel R. Esquivel",
"Alan Estrada", "Sergio Fachelli", "Joss Favela", "Felo (cantante)", "Alejandro Fernández", 
"Alex Fernández (cantante)", "Pedro Fernández (cantante)", "Vicente Fernández",
"Fernando Fernández (cantante mexicano)", "José Manuel Figueroa", "Alejandro Filio",
"Flavio César", "Salvador Flores Rivera", "José Fors", "Francisco Fourcade",
"Héctor Fuentes (actor)", "Ismael Fuentes de Garay", "Francisco Gabilondo Soler",
"Patricio Gallardo", "Fernando García Herrera", "Leonel García",
"Marcelo García (artista)", "Vicente Garrido Calderón", "Miguel Garza",
"Luis Gatica (actor)", "Daniel Gaytán", "Alfredo Gil", "Gilberto (Sahuaripa) Valenzuela",
"Joaquín A. González", "Demetrio González", "Eulalio González", 
"Rockdrigo (cantante)", "Roger González", "Enrique Guzmán (cantante)",
"David Haro", "Carlos Hauptvogel", "Hermanos Martínez Gil", "Magos Herrera",
"Nicho Hinojosa", "Andrés Huesca", "Micky Huidobro", "Benny Ibarra",
"Pedro Infante", "Israel Zarzosa", "Jan (actor)", "Pepe Jara", "Enrique Jaso",
"Joel Jáuregui", "Adan Jodorowsky", "José Joel", "Roberto Jordán", "José José",
"José Guadalupe Esparza", "Juan Gabriel", "Kiko (cantante)", "Johnny Laboriel", 
"Imanol Landeta", "Manuel Landeta", "Agustín Lara", "Gustavo Lara", 
"León Larregui", "Carlos Law", "Carlos Lico", "Lo dijo el corazón", 
"Jaime López", "Álex Lora", "Lorenzo Antonio", "Lorenzo de Monteclaro",
"Los dúo", "Leonardo de Lozanne", "Alfonso Lugo", "Luis Miguel", "José Madero",
"Oscar Madrigal", "Armando Manzanero", "Marco Antonio Muñiz", 
"Jarris Margalli", "Paco de María", "Kalimba (cantante)", "Charlie (cantante)",
"Chucho Martínez Gil", "Mauricio Martínez (actor)", "MC Luka", "Nacho Méndez",
"Tomás Méndez", "Elmar Mendoza", "Miguel Cantalapiedra", "Manuel Mijares", "Pablo Montero",
"Lalo Mora", "Jorge Muñiz", "Manolo Muñoz", "Edén Muñoz", "Yago Muñoz", "José María Napoleón",
"Chucho Navarro", "Chucho Navarro Jr", "Jesús Navarro (cantante)", "Jorge Negrete", "Alfredo Olivas",
"Fernando Olvera", "Cristóbal Orellana", "Eduardo Palomo", "Joaquín Pardavé", "Mane de la Parra",
"Eduardo Arozamena Pasarón", "Espinoza Paz", "Arturo Peniche", "Ezequiel Peña", "Luis Pérez Meza", 
"El Chapo de Sinaloa", "Celso Piña", "Pablo Portillo", "Julio Preciado", "Paulo César Quevedo",
"Mario Quintero Lara", "Daniel Ramírez Sayalero", "Agustín Ramírez", "Joselo Rangel",
"Gerardo Reyes", "Javier Reyes", "Jorge Reyes (músico)", "Reyli Barba", "Cornelio Reyna",
"Ángela Aguilar", "Majo Aguilar", "Patricia Aguirre", "Cherry Ahava", "Ilean Almaguer",
"Emilia Almazán", "Alondra (cantante)", "Alquimia (cantante)", "Sofía Álvarez (actriz nacida en 1913)",
"Amandititita", "Flor Amargo", "Ana Valeria (Anaís)", "Ana Victoria", "Chantal Andere",
"Fanny Anitúa", "Aracely Arámbula", "Aranza", "Arianna (cantante)", "Fernanda Arozqueta",
"Ashley Grace", "Alejandra Ávalos", "Lidia Ávila", "María Eva Avilés", "Ana Bárbara", 
"María Barracuda", "Alix Bauer", "Beatriz Adriana", "Ingrid Beaujean", "Belinda (cantante)",
"Lola Beltrán", "María Bernal", "Brenda Bezares", "Fey", "María Bonilla", "María Raquenel", 
"Marcela Bovio", "Erika Buenfil", "Jessy Bulbo", "Elba Cabrera", "Stephie Caire", "Camila Fernández",
"Usuario:CamiloAmargo/Taller", "Abril Campillo", "Chela Campos", "Silvia Campos", 
"Sofía Cancino de Cuevas", "Nora Cano", "Laura Denisse", "Paty Cantú", "Laura Caro", "Vikki Carr",
"Rosa de Castilla (cantante)", "Irán Castillo", "Verónica Castro", "Karina Catalán", "Payín Cejudo",
"Alma Cero", "María Chacón", "Zoe Chamberlain", "Jannette Chao", "Sara Cobo", "Verónika con K",
"Ninel Conde", "Mar Contreras", "Marbella Corella", "Ingrid Coronado", "Millie Corretjer",
"Lolita Cortés", "Usuario:CRAW309/Paquita La Del Barrio", "Natalia Cruz (cantante)",
"Aída Cuevas", "Niurka Curbelo", "Lupita D'Alessio", "Lolita de la Colina", "Marisa De Lille",
"Amanda del Llano", "María del Sol", "Lila Deneken", "Ana Díaz Aceves",
"Karla Díaz-Leal Arreguín", "Jessica Díaz", "Dora María", "Irma Dorantes",
"Dulce (cantante)", "Natasha Dupeyrón", "María Duval (actriz mexicana)",
"Kika Edgar", "Elán", "Maite Embil", "Evita (actriz)", "Liliana Felipe", "María Félix",
"Flor Silvestre", "Laura Flores", "Renata Flores (actriz)", "Adrianna Foster",
"Sonia Furió", "Ana Gabriel", "Gaby Garza", "Nina Galindo", "Marcela Gándara",
"Mayté Gaos", "Eva Garza", "Mariana Garza", "Biby Gaytán", "Gloria Aura",
"María Isabel Gómez Bell", "Crisanta Gómez", "Ana María González (cantante mexicana)",
"Eiza González", "Irma González", "Sherlyn González", "Paulina Goto",
"Guadalupe la Chinaca", "Paola Guanche", "Maribel Guardia", "Ely Guerra",
"María Inés Guerra", "Rita Guerrero", "Denisse Guerrero", "Olga Guillot",
"Alejandra Guzmán", "Astrid Hadad", "Hanna Nicole", "Susana Harp",
 "Hermanas Padilla", "Lorena Herrera", "Norma Herrera",
"Guillermina Higareda", "Kenya Hijuelos", "Paulina Holguin", "Joy Huerta",
"Tessa Ía", "Ilse (cantante)", "Dalia Inés", "Esperanza Iris", "Violeta Isfel",
"Ivonne (cantante)", "Mary Jiménez", "Jolette", "Dora Juárez Kiczkovsky",
"Alicia Juárez", "Julissa", "Denisse de Kalafe", "María Katzarava", 
"Vitola (actriz)", "La Panchita (cantante)", "La Prieta Linda", "Ella Laboriel",
"Natalia Lafourcade", "Andrea Lagunés", "Libertad Lamarque", "Avelina Landín",
"María Luisa Landín", "Amanda Ledesma", "Leiden (cantante)", "Eugenia León",
"María León (cantante)", "Cecy Leos", "Tania Libertad", "Lilo (cantante)", "Lisset",
"Litzy", "Melissa (Jeans)", "Sonia López", "Lorena Marlene Cortinas Galván", "Morganna Love",
"Verónica Loyo", "Alexa Lozano", "Allisson Lozz", "Daniela Luján", "Yrma Lydya", "Lynda", "Amalia Macías",
"Mariana Magaña", "Malukah", "Loreli Mancilla", "Patricia Manterola", "Niurka Marcos", "María Enriqueta",
"Angélica María", "Marilú (cantante)", "Diana Mariscal", "Lucila Mariscal", "María Elena Marqués",
"Darina", "Edith Márquez", "Martha Duhalt", "La Torcacita", "Carla Mauri", "Graciela Mauri", 
"Brissia Mayagoitia", "Sofía Mayorga", "Carla Medina", "Penélope Menchaca", "Lucía Méndez (actriz)",
"Rossy Mendoza", "Amalia Mendoza", "Geo Meneses"
]

export default artist;